name: Manual Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "请输入版本号 (例如: v1.0.0)"
        default: "dev"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: 设置版本号
        id: set_version
        run: echo "version=$GITHUB_REF" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

      - name: 获取用户输入版本号
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装构建工具
        run: |
          pip install meson ninja
          # 如果需要其他依赖，添加在这里

      - name: 构建项目
        run: |
          # 根据你的项目调整构建命令
          meson setup -Dversion=${{ env.version }} build
          ninja -C build

      - name: 创建 Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          name: 发布 ${{ env.version }}
          body: |
            自动发布的构建版本
          files: build/*  # 修改为实际的构建输出路径
          draft: false
          prerelease: ${{ startsWith(env.version, 'dev') }}
